services:
  mongo:
    image: mongo:6
    container_name: shared-mongo
    ports:
      - "27017:27017"
    volumes:
      - mychat-dev_mongo_data:/data/db
    networks:
      - mychat-net

  auth:
    build:
      context: ../mychat-auth
    ports:
      - "4001:4001"
    env_file:
      - ../mychat-auth/.env
    depends_on:
      - mongo
      - redis
    networks:
      - mychat-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mychat-net

  room:
    build:
      context: ../mychat-room
    container_name: mychat-room
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://shared-mongo:27017/mychat
    depends_on:
      - mongo
    networks:
      - mychat-net

  chat:
    build:
      context: ../mychat-chat
    container_name: mychat-chat
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://shared-mongo:27017/mychat
      - REDIS_URL=redis:6379
      - JWT_SECRET=your-super-secret-key
    depends_on:
      - mongo
      - redis
    networks:
      - mychat-net

  message:
    build:
      context: ../mychat-message
    container_name: mychat-message
    ports:
      - "5002:5002"
    env_file:
      - ../mychat-message/.env
    environment:
      - MONGO_URI=mongodb://shared-mongo:27017/mychat
      - REDIS_URL=redis:6379
      - JWT_SECRET=your-super-secret-key
    depends_on:
      - mongo
      - redis
    networks:
      - mychat-net


volumes:
  mychat-dev_mongo_data:
    external: true

networks:
  mychat-net:
    external: true
